var files =
[
    [ "algorithms.hpp", "algorithms_8hpp.html", "algorithms_8hpp" ],
    [ "alias_node.hpp", "alias__node_8hpp_source.html", null ],
    [ "angle.hpp", "angle_8hpp_source.html", null ],
    [ "any.hpp", "any_8hpp_source.html", null ],
    [ "any_map.hpp", "any__map_8hpp.html", "any__map_8hpp" ],
    [ "apply.hpp", "apply_8hpp.html", "apply_8hpp" ],
    [ "apply_domain.hpp", "apply__domain_8hpp_source.html", null ],
    [ "array_domain.hpp", "array__domain_8hpp_source.html", null ],
    [ "ossia-max/src/attribute.hpp", "ossia-max_2src_2attribute_8hpp_source.html", null ],
    [ "ossia-pd/src/attribute.hpp", "ossia-pd_2src_2attribute_8hpp_source.html", null ],
    [ "attributes.hpp", "attributes_8hpp.html", "attributes_8hpp" ],
    [ "audio_parameter.hpp", "audio__parameter_8hpp_source.html", null ],
    [ "automation.hpp", "automation_8hpp.html", [
      [ "automation", "classossia_1_1automation.html", "classossia_1_1automation" ]
    ] ],
    [ "behavior.hpp", "behavior_8hpp.html", "behavior_8hpp" ],
    [ "behavior_variant_impl.hpp", "behavior__variant__impl_8hpp_source.html", null ],
    [ "callback_container.hpp", "callback__container_8hpp.html", [
      [ "invalid_callback_error", "structossia_1_1invalid__callback__error.html", "structossia_1_1invalid__callback__error" ],
      [ "callback_container", "classossia_1_1callback__container.html", "classossia_1_1callback__container" ]
    ] ],
    [ "channel.hpp", "channel_8hpp_source.html", null ],
    [ "clamp_visitors.hpp", "clamp__visitors_8hpp_source.html", null ],
    [ "network/oscquery/detail/client.hpp", "network_2oscquery_2detail_2client_8hpp_source.html", null ],
    [ "max/src/client.hpp", "max_2src_2client_8hpp_source.html", null ],
    [ "pd/src/client.hpp", "pd_2src_2client_8hpp_source.html", null ],
    [ "clock.hpp", "clock_8hpp_source.html", null ],
    [ "color.hpp", "color_8hpp_source.html", null ],
    [ "complex_type.hpp", "complex__type_8hpp_source.html", null ],
    [ "config.hpp", "config_8hpp_source.html", null ],
    [ "connection.hpp", "connection_8hpp_source.html", null ],
    [ "context.hpp", "context_8hpp.html", "context_8hpp" ],
    [ "curve.hpp", "curve_8hpp.html", "curve_8hpp" ],
    [ "curve_abstract.hpp", "curve__abstract_8hpp.html", "curve__abstract_8hpp" ],
    [ "curve_segment.hpp", "curve__segment_8hpp.html", "curve__segment_8hpp" ],
    [ "curve_value_visitor.hpp", "curve__value__visitor_8hpp_source.html", null ],
    [ "custom_state.hpp", "custom__state_8hpp.html", [
      [ "custom_state", "classossia_1_1custom__state.html", "classossia_1_1custom__state" ]
    ] ],
    [ "data.hpp", "data_8hpp_source.html", null ],
    [ "dataflow.hpp", "dataflow_8hpp_source.html", null ],
    [ "dataflow_fwd.hpp", "dataflow__fwd_8hpp_source.html", null ],
    [ "dataspace.hpp", "dataspace_8hpp_source.html", null ],
    [ "dataspace_base.hpp", "dataspace__base_8hpp_source.html", null ],
    [ "dataspace_base_defs_fwd.hpp", "dataspace__base__defs__fwd_8hpp_source.html", null ],
    [ "dataspace_base_fwd.hpp", "dataspace__base__fwd_8hpp_source.html", null ],
    [ "dataspace_base_variants.hpp", "dataspace__base__variants_8hpp_source.html", null ],
    [ "dataspace_convert.hpp", "dataspace__convert_8hpp_source.html", null ],
    [ "dataspace_fwd.hpp", "dataspace__fwd_8hpp_source.html", null ],
    [ "dataspace_merge.hpp", "dataspace__merge_8hpp_source.html", null ],
    [ "dataspace_parse.hpp", "dataspace__parse_8hpp_source.html", null ],
    [ "detail/dataspace_parse.hpp", "detail_2dataspace__parse_8hpp_source.html", null ],
    [ "dataspace_strong_variants.hpp", "dataspace__strong__variants_8hpp_source.html", null ],
    [ "dataspace_variant_visitors.hpp", "dataspace__variant__visitors_8hpp_source.html", null ],
    [ "dataspace_visitors.hpp", "dataspace__visitors_8hpp.html", "dataspace__visitors_8hpp" ],
    [ "debug.hpp", "debug_8hpp.html", "debug_8hpp" ],
    [ "destination.hpp", "destination_8hpp.html", "destination_8hpp" ],
    [ "destination_index.hpp", "destination__index_8hpp.html", "destination__index_8hpp" ],
    [ "destination_qualifiers.hpp", "destination__qualifiers_8hpp_source.html", null ],
    [ "network/base/device.hpp", "network_2base_2device_8hpp_source.html", null ],
    [ "max/src/device.hpp", "max_2src_2device_8hpp_source.html", null ],
    [ "pd/src/device.hpp", "pd_2src_2device_8hpp_source.html", null ],
    [ "ossia-max/src/device_base.hpp", "ossia-max_2src_2device__base_8hpp_source.html", null ],
    [ "ossia-pd/src/device_base.hpp", "ossia-pd_2src_2device__base_8hpp_source.html", null ],
    [ "distance.hpp", "distance_8hpp_source.html", null ],
    [ "domain.hpp", "domain_8hpp_source.html", null ],
    [ "domain_base.hpp", "domain__base_8hpp.html", "domain__base_8hpp" ],
    [ "domain_base_impl.hpp", "domain__base__impl_8hpp_source.html", null ],
    [ "domain_base_variant.hpp", "domain__base__variant_8hpp_source.html", null ],
    [ "domain_conversion.hpp", "domain__conversion_8hpp_source.html", null ],
    [ "domain_functions.hpp", "domain__functions_8hpp_source.html", null ],
    [ "domain_fwd.hpp", "domain__fwd_8hpp_source.html", null ],
    [ "domain_to_json.hpp", "domain__to__json_8hpp_source.html", null ],
    [ "domain_variant_impl.hpp", "domain__variant__impl_8hpp_source.html", null ],
    [ "easing.hpp", "easing_8hpp.html", null ],
    [ "editor.hpp", "editor_8hpp_source.html", null ],
    [ "empty.hpp", "empty_8hpp_source.html", null ],
    [ "exception.hpp", "exception_8hpp_source.html", null ],
    [ "editor/exceptions.hpp", "editor_2exceptions_8hpp_source.html", null ],
    [ "network/exceptions.hpp", "network_2exceptions_8hpp_source.html", null ],
    [ "execution_state.hpp", "execution__state_8hpp_source.html", null ],
    [ "expression.hpp", "expression_8hpp.html", "expression_8hpp" ],
    [ "expression_atom.hpp", "expression__atom_8hpp.html", [
      [ "expression_atom", "classossia_1_1expressions_1_1expression__atom.html", "classossia_1_1expressions_1_1expression__atom" ]
    ] ],
    [ "expression_bool.hpp", "expression__bool_8hpp.html", [
      [ "expression_bool", "classossia_1_1expressions_1_1expression__bool.html", "classossia_1_1expressions_1_1expression__bool" ]
    ] ],
    [ "expression_composition.hpp", "expression__composition_8hpp.html", [
      [ "expression_composition", "classossia_1_1expressions_1_1expression__composition.html", "classossia_1_1expressions_1_1expression__composition" ]
    ] ],
    [ "expression_fwd.hpp", "expression__fwd_8hpp.html", "expression__fwd_8hpp" ],
    [ "expression_generic.hpp", "expression__generic_8hpp_source.html", null ],
    [ "expression_not.hpp", "expression__not_8hpp.html", [
      [ "expression_not", "classossia_1_1expressions_1_1expression__not.html", "classossia_1_1expressions_1_1expression__not" ]
    ] ],
    [ "expression_pulse.hpp", "expression__pulse_8hpp.html", [
      [ "expression_pulse", "classossia_1_1expressions_1_1expression__pulse.html", "classossia_1_1expressions_1_1expression__pulse" ]
    ] ],
    [ "extended_types.hpp", "extended__types_8hpp_source.html", null ],
    [ "functional_state.hpp", "functional__state_8hpp_source.html", null ],
    [ "gain.hpp", "gain_8hpp_source.html", null ],
    [ "generic_device.hpp", "generic__device_8hpp_source.html", null ],
    [ "generic_domain.hpp", "generic__domain_8hpp_source.html", null ],
    [ "generic_node.hpp", "generic__node_8hpp_source.html", null ],
    [ "generic_parameter.hpp", "generic__parameter_8hpp_source.html", null ],
    [ "get_query_parser.hpp", "get__query__parser_8hpp_source.html", null ],
    [ "git_info.h", "git__info_8h_source.html", null ],
    [ "gradient.hpp", "gradient_8hpp_source.html", null ],
    [ "graph.hpp", "graph_8hpp_source.html", null ],
    [ "graph_edge.hpp", "graph__edge_8hpp_source.html", null ],
    [ "graph_node.hpp", "graph__node_8hpp_source.html", null ],
    [ "http.hpp", "http_8hpp_source.html", null ],
    [ "http_client.hpp", "http__client_8hpp_source.html", null ],
    [ "http_device.hpp", "http__device_8hpp_source.html", null ],
    [ "http_node.hpp", "http__node_8hpp_source.html", null ],
    [ "http_parameter.hpp", "http__parameter_8hpp_source.html", null ],
    [ "http_parameter_data.hpp", "http__parameter__data_8hpp_source.html", null ],
    [ "http_protocol.hpp", "http__protocol_8hpp_source.html", null ],
    [ "http_query_parser.hpp", "http__query__parser_8hpp.html", "http__query__parser_8hpp" ],
    [ "impulse.hpp", "impulse_8hpp_source.html", null ],
    [ "instantiations.hpp", "instantiations_8hpp_source.html", null ],
    [ "js_utilities.hpp", "js__utilities_8hpp_source.html", null ],
    [ "json.hpp", "json_8hpp_source.html", null ],
    [ "json_fwd.hpp", "json__fwd_8hpp_source.html", null ],
    [ "json_parser.hpp", "json__parser_8hpp_source.html", null ],
    [ "json_query_parser.hpp", "json__query__parser_8hpp_source.html", null ],
    [ "json_reader_detail.hpp", "json__reader__detail_8hpp_source.html", null ],
    [ "json_writer.hpp", "json__writer_8hpp_source.html", null ],
    [ "json_writer_detail.hpp", "json__writer__detail_8hpp_source.html", null ],
    [ "linear.hpp", "linear_8hpp_source.html", null ],
    [ "list_units.hpp", "list__units_8hpp_source.html", null ],
    [ "listening.hpp", "listening_8hpp_source.html", null ],
    [ "local.hpp", "local_8hpp_source.html", null ],
    [ "locked_container.hpp", "locked__container_8hpp.html", [
      [ "locked_container", "classossia_1_1locked__container.html", "classossia_1_1locked__container" ]
    ] ],
    [ "detail/logger.hpp", "detail_2logger_8hpp_source.html", null ],
    [ "max/src/logger.hpp", "max_2src_2logger_8hpp_source.html", null ],
    [ "pd/src/logger.hpp", "pd_2src_2logger_8hpp_source.html", null ],
    [ "loop.hpp", "loop_8hpp.html", [
      [ "loop", "classossia_1_1loop.html", "classossia_1_1loop" ]
    ] ],
    [ "make_unit.hpp", "make__unit_8hpp_source.html", null ],
    [ "make_value.hpp", "make__value_8hpp_source.html", null ],
    [ "mapper.hpp", "mapper_8hpp.html", [
      [ "mapper", "classossia_1_1mapper.html", "classossia_1_1mapper" ]
    ] ],
    [ "math.hpp", "math_8hpp.html", "math_8hpp" ],
    [ "message.hpp", "message_8hpp.html", [
      [ "message", "structossia_1_1message.html", "structossia_1_1message" ]
    ] ],
    [ "message_generator.hpp", "message__generator_8hpp_source.html", null ],
    [ "message_queue.hpp", "message__queue_8hpp_source.html", null ],
    [ "metatypes.hpp", "metatypes_8hpp_source.html", null ],
    [ "metronome.hpp", "metronome_8hpp_source.html", null ],
    [ "midi.hpp", "midi_8hpp_source.html", null ],
    [ "midi_device.hpp", "midi__device_8hpp_source.html", null ],
    [ "midi_impl.hpp", "midi__impl_8hpp_source.html", null ],
    [ "midi_node.hpp", "midi__node_8hpp_source.html", null ],
    [ "midi_parameter.hpp", "midi__parameter_8hpp_source.html", null ],
    [ "midi_protocol.hpp", "midi__protocol_8hpp_source.html", null ],
    [ "min_max.hpp", "min__max_8hpp_source.html", null ],
    [ "minuit.hpp", "minuit_8hpp_source.html", null ],
    [ "minuit_common.hpp", "minuit__common_8hpp_source.html", null ],
    [ "minuit_name_table.hpp", "minuit__name__table_8hpp_source.html", null ],
    [ "minuit_parser.hpp", "minuit__parser_8hpp_source.html", null ],
    [ "misc_visitors.hpp", "misc__visitors_8hpp_source.html", null ],
    [ "ossia-max/src/model.hpp", "ossia-max_2src_2model_8hpp_source.html", null ],
    [ "ossia-pd/src/model.hpp", "ossia-pd_2src_2model_8hpp_source.html", null ],
    [ "mutex.hpp", "mutex_8hpp_source.html", null ],
    [ "name_utils.hpp", "name__utils_8hpp_source.html", null ],
    [ "name_validation.hpp", "name__validation_8hpp_source.html", null ],
    [ "network.hpp", "network_8hpp_source.html", null ],
    [ "network_logger.hpp", "network__logger_8hpp_source.html", null ],
    [ "node.hpp", "node_8hpp_source.html", null ],
    [ "node_attributes.hpp", "node__attributes_8hpp.html", "node__attributes_8hpp" ],
    [ "ossia-max/src/node_base.hpp", "ossia-max_2src_2node__base_8hpp_source.html", null ],
    [ "ossia-pd/src/node_base.hpp", "ossia-pd_2src_2node__base_8hpp_source.html", null ],
    [ "node_functions.hpp", "node__functions_8hpp.html", "node__functions_8hpp" ],
    [ "node_process.hpp", "node__process_8hpp_source.html", null ],
    [ "numeric_domain.hpp", "numeric__domain_8hpp_source.html", null ],
    [ "ossia-max/src/object_base.hpp", "ossia-max_2src_2object__base_8hpp_source.html", null ],
    [ "ossia-pd/src/object_base.hpp", "ossia-pd_2src_2object__base_8hpp_source.html", null ],
    [ "operators.hpp", "operators_8hpp_source.html", null ],
    [ "optional.hpp", "optional_8hpp_source.html", null ],
    [ "orientation.hpp", "orientation_8hpp_source.html", null ],
    [ "detail/osc.hpp", "detail_2osc_8hpp_source.html", null ],
    [ "osc.hpp", "osc_8hpp_source.html", null ],
    [ "osc_fwd.hpp", "osc__fwd_8hpp_source.html", null ],
    [ "osc_receive.hpp", "osc__receive_8hpp_source.html", null ],
    [ "oscquery_client.hpp", "oscquery__client_8hpp_source.html", null ],
    [ "oscquery_mirror.hpp", "oscquery__mirror_8hpp_source.html", null ],
    [ "oscquery_server.hpp", "oscquery__server_8hpp_source.html", null ],
    [ "ossia-c.h", "ossia-c_8h.html", "ossia-c_8h" ],
    [ "ossia-cpp98.hpp", "ossia-cpp98_8hpp_source.html", null ],
    [ "ossia-java.hpp", "ossia-java_8hpp_source.html", null ],
    [ "ossia-max.hpp", "ossia-max_8hpp_source.html", null ],
    [ "ossia-pd.hpp", "ossia-pd_8hpp_source.html", null ],
    [ "ossia.hpp", "ossia_8hpp_source.html", null ],
    [ "ossia_log.h", "ossia__log_8h_source.html", null ],
    [ "ossia_object.hpp", "ossia__object_8hpp_source.html", null ],
    [ "ossia_utils.hpp", "ossia__utils_8hpp_source.html", null ],
    [ "OssiaUI.h", "_ossia_u_i_8h_source.html", null ],
    [ "outbound_visitor.hpp", "outbound__visitor_8hpp_source.html", null ],
    [ "outbound_visitor_impl.hpp", "outbound__visitor__impl_8hpp_source.html", null ],
    [ "network/base/parameter.hpp", "network_2base_2parameter_8hpp_source.html", null ],
    [ "max/src/parameter.hpp", "max_2src_2parameter_8hpp_source.html", null ],
    [ "pd/src/parameter.hpp", "pd_2src_2parameter_8hpp_source.html", null ],
    [ "ossia-max/src/parameter_base.hpp", "ossia-max_2src_2parameter__base_8hpp_source.html", null ],
    [ "ossia-pd/src/parameter_base.hpp", "ossia-pd_2src_2parameter__base_8hpp_source.html", null ],
    [ "parameter_data.hpp", "parameter__data_8hpp_source.html", null ],
    [ "parameter_properties.hpp", "parameter__properties_8hpp_source.html", null ],
    [ "path.hpp", "path_8hpp_source.html", null ],
    [ "phidgets.hpp", "phidgets_8hpp_source.html", null ],
    [ "phidgets_device.hpp", "phidgets__device_8hpp_source.html", null ],
    [ "phidgets_node.hpp", "phidgets__node_8hpp_source.html", null ],
    [ "phidgets_parameter.hpp", "phidgets__parameter_8hpp_source.html", null ],
    [ "phidgets_parameter_data.hpp", "phidgets__parameter__data_8hpp_source.html", null ],
    [ "phidgets_protocol.hpp", "phidgets__protocol_8hpp_source.html", null ],
    [ "phidgetspp.hpp", "phidgetspp_8hpp_source.html", null ],
    [ "port.hpp", "port_8hpp_source.html", null ],
    [ "position.hpp", "position_8hpp_source.html", null ],
    [ "power.hpp", "power_8hpp_source.html", null ],
    [ "prefix.hpp", "prefix_8hpp_source.html", null ],
    [ "preset.h", "preset_8h_source.html", null ],
    [ "preset.hpp", "preset_8hpp_source.html", null ],
    [ "protocol.hpp", "protocol_8hpp_source.html", null ],
    [ "ptr_container.hpp", "ptr__container_8hpp.html", "ptr__container_8hpp" ],
    [ "qml_autom.hpp", "qml__autom_8hpp_source.html", null ],
    [ "qml_cond.hpp", "qml__cond_8hpp_source.html", null ],
    [ "qml_context.hpp", "qml__context_8hpp_source.html", null ],
    [ "qml_device.hpp", "qml__device_8hpp_source.html", null ],
    [ "qml_exec.hpp", "qml__exec_8hpp_source.html", null ],
    [ "qml_interval.hpp", "qml__interval_8hpp_source.html", null ],
    [ "qml_logger.hpp", "qml__logger_8hpp_source.html", null ],
    [ "qml_loop.hpp", "qml__loop_8hpp_source.html", null ],
    [ "qml_mapping.hpp", "qml__mapping_8hpp_source.html", null ],
    [ "qml_model_property.hpp", "qml__model__property_8hpp_source.html", null ],
    [ "qml_node.hpp", "qml__node_8hpp_source.html", null ],
    [ "qml_node_base.hpp", "qml__node__base_8hpp_source.html", null ],
    [ "qml_parameter.hpp", "qml__parameter_8hpp_source.html", null ],
    [ "qml_plugin.hpp", "qml__plugin_8hpp_source.html", null ],
    [ "qml_property.hpp", "qml__property_8hpp_source.html", null ],
    [ "qml_property_reader.hpp", "qml__property__reader_8hpp_source.html", null ],
    [ "qml_scenario.hpp", "qml__scenario_8hpp_source.html", null ],
    [ "qml_script.hpp", "qml__script_8hpp_source.html", null ],
    [ "qml_signal.hpp", "qml__signal_8hpp_source.html", null ],
    [ "qml_state.hpp", "qml__state_8hpp_source.html", null ],
    [ "qml_sync.hpp", "qml__sync_8hpp_source.html", null ],
    [ "qml_util.hpp", "qml__util_8hpp_source.html", null ],
    [ "qt_device.hpp", "qt__device_8hpp_source.html", null ],
    [ "qt_object_node.hpp", "qt__object__node_8hpp_source.html", null ],
    [ "qt_property_node.hpp", "qt__property__node_8hpp_source.html", null ],
    [ "query_parser.hpp", "query__parser_8hpp_source.html", null ],
    [ "receiver.hpp", "receiver_8hpp_source.html", null ],
    [ "ossia-max/src/remote.hpp", "ossia-max_2src_2remote_8hpp_source.html", null ],
    [ "ossia-pd/src/remote.hpp", "ossia-pd_2src_2remote_8hpp_source.html", null ],
    [ "result.h", "result_8h_source.html", null ],
    [ "safe_vec.hpp", "safe__vec_8hpp_source.html", null ],
    [ "scenario.hpp", "scenario_8hpp_source.html", null ],
    [ "sender.hpp", "sender_8hpp_source.html", null ],
    [ "sensors.hpp", "sensors_8hpp_source.html", null ],
    [ "serial.hpp", "serial_8hpp_source.html", null ],
    [ "serial_device.hpp", "serial__device_8hpp_source.html", null ],
    [ "serial_node.hpp", "serial__node_8hpp_source.html", null ],
    [ "serial_parameter.hpp", "serial__parameter_8hpp_source.html", null ],
    [ "serial_parameter_data.hpp", "serial__parameter__data_8hpp_source.html", null ],
    [ "serial_protocol.hpp", "serial__protocol_8hpp_source.html", null ],
    [ "server.hpp", "server_8hpp_source.html", null ],
    [ "sin.hpp", "sin_8hpp_source.html", null ],
    [ "speed.hpp", "speed_8hpp_source.html", null ],
    [ "spline.hpp", "spline_8hpp_source.html", null ],
    [ "state.hpp", "state_8hpp.html", "state_8hpp" ],
    [ "state_element.hpp", "state__element_8hpp.html", "state__element_8hpp" ],
    [ "state_element_fwd.hpp", "state__element__fwd_8hpp.html", "state__element__fwd_8hpp" ],
    [ "state_execution_visitor.hpp", "state__execution__visitor_8hpp_source.html", null ],
    [ "state_flatten_visitor.hpp", "state__flatten__visitor_8hpp_source.html", null ],
    [ "state_print_visitor.hpp", "state__print__visitor_8hpp_source.html", null ],
    [ "string_map.hpp", "string__map_8hpp.html", "string__map_8hpp" ],
    [ "detail/string_view.hpp", "detail_2string__view_8hpp_source.html", null ],
    [ "network/osc/detail/string_view.hpp", "network_2osc_2detail_2string__view_8hpp_source.html", null ],
    [ "temperature.hpp", "temperature_8hpp_source.html", null ],
    [ "thread.hpp", "thread_8hpp_source.html", null ],
    [ "time.hpp", "time_8hpp_source.html", null ],
    [ "time_event.hpp", "time__event_8hpp.html", [
      [ "time_event", "classossia_1_1time__event.html", "classossia_1_1time__event" ]
    ] ],
    [ "time_interval.hpp", "time__interval_8hpp.html", [
      [ "time_interval", "classossia_1_1time__interval.html", "classossia_1_1time__interval" ]
    ] ],
    [ "time_process.hpp", "time__process_8hpp.html", [
      [ "time_process", "classossia_1_1time__process.html", "classossia_1_1time__process" ]
    ] ],
    [ "time_sync.hpp", "time__sync_8hpp.html", [
      [ "time_sync", "classossia_1_1time__sync.html", "classossia_1_1time__sync" ]
    ] ],
    [ "time_value.hpp", "time__value_8hpp.html", "time__value_8hpp" ],
    [ "tinyspline.h", "tinyspline_8h_source.html", null ],
    [ "tinysplinecpp.h", "tinysplinecpp_8h_source.html", null ],
    [ "typetag.hpp", "typetag_8hpp_source.html", null ],
    [ "ossia-max/src/utils.hpp", "ossia-max_2src_2utils_8hpp_source.html", null ],
    [ "ossia-pd/src/utils.hpp", "ossia-pd_2src_2utils_8hpp_source.html", null ],
    [ "value.hpp", "value_8hpp.html", "value_8hpp" ],
    [ "value_algorithms.hpp", "value__algorithms_8hpp_source.html", null ],
    [ "value_base.hpp", "value__base_8hpp_source.html", null ],
    [ "value_callback.hpp", "value__callback_8hpp_source.html", null ],
    [ "value_comparison.hpp", "value__comparison_8hpp_source.html", null ],
    [ "value_conversion.hpp", "value__conversion_8hpp.html", "value__conversion_8hpp" ],
    [ "value_conversion_impl.hpp", "value__conversion__impl_8hpp_source.html", null ],
    [ "value_metatypes.hpp", "value__metatypes_8hpp_source.html", null ],
    [ "value_parse_impl.hpp", "value__parse__impl_8hpp_source.html", null ],
    [ "value_set_domain.hpp", "value__set__domain_8hpp_source.html", null ],
    [ "value_to_json.hpp", "value__to__json_8hpp_source.html", null ],
    [ "value_traits.hpp", "value__traits_8hpp.html", "value__traits_8hpp" ],
    [ "value_variant_impl.hpp", "value__variant__impl_8hpp_source.html", null ],
    [ "value_with_unit.hpp", "value__with__unit_8hpp_source.html", null ],
    [ "vec.hpp", "vec_8hpp_source.html", null ],
    [ "ossia-max/src/view.hpp", "ossia-max_2src_2view_8hpp_source.html", null ],
    [ "ossia-pd/src/view.hpp", "ossia-pd_2src_2view_8hpp_source.html", null ],
    [ "websocket_log_sink.hpp", "websocket__log__sink_8hpp_source.html", null ],
    [ "ws_generic_client.hpp", "ws__generic__client_8hpp_source.html", null ],
    [ "ws_generic_client_device.hpp", "ws__generic__client__device_8hpp_source.html", null ],
    [ "ws_generic_client_node.hpp", "ws__generic__client__node_8hpp_source.html", null ],
    [ "ws_generic_client_parameter.hpp", "ws__generic__client__parameter_8hpp_source.html", null ],
    [ "ws_generic_client_parameter_data.hpp", "ws__generic__client__parameter__data_8hpp_source.html", null ],
    [ "ws_generic_client_protocol.hpp", "ws__generic__client__protocol_8hpp_source.html", null ],
    [ "zeroconf.hpp", "zeroconf_8hpp_source.html", null ]
];