var hierarchy =
[
    [ "ossia::net::alias_node", "classossia_1_1net_1_1alias__node.html", null ],
    [ "ossia::regex_path::any_node", "structossia_1_1regex__path_1_1any__node.html", null ],
    [ "ossia::regex_path::any_path", "structossia_1_1regex__path_1_1any__path.html", null ],
    [ "ossia::bad_request_error", "structossia_1_1bad__request__error.html", null ],
    [ "ossia::max::box_hierachy", "classossia_1_1max_1_1box__hierachy.html", null ],
    [ "ossia::callback_container< T >", "classossia_1_1callback__container.html", [
      [ "ossia::expressions::expression_atom", "classossia_1_1expressions_1_1expression__atom.html", null ],
      [ "ossia::expressions::expression_bool", "classossia_1_1expressions_1_1expression__bool.html", null ],
      [ "ossia::expressions::expression_composition", "classossia_1_1expressions_1_1expression__composition.html", null ],
      [ "ossia::expressions::expression_not", "classossia_1_1expressions_1_1expression__not.html", null ],
      [ "ossia::expressions::expression_pulse", "classossia_1_1expressions_1_1expression__pulse.html", null ]
    ] ],
    [ "ossia::callback_container< std::function< void()> >", "classossia_1_1callback__container.html", null ],
    [ "ossia::callback_container< std::function< void(bool)> >", "classossia_1_1callback__container.html", null ],
    [ "ossia::callback_container< value_callback >", "classossia_1_1callback__container.html", [
      [ "ossia::net::parameter_base", "classossia_1_1net_1_1parameter__base.html", [
        [ "ossia::net::generic_parameter", "classossia_1_1net_1_1generic__parameter.html", null ]
      ] ]
    ] ],
    [ "ossia::connection_error", "structossia_1_1connection__error.html", null ],
    [ "Contains", "class_contains.html", null ],
    [ "ossia::context", "structossia_1_1context.html", null ],
    [ "ossia::curve_abstract", "classossia_1_1curve__abstract.html", [
      [ "ossia::constant_curve", "classossia_1_1constant__curve.html", null ],
      [ "ossia::curve< X, Y >", "classossia_1_1curve.html", null ]
    ] ],
    [ "ossia::custom_state", "classossia_1_1custom__state.html", null ],
    [ "Destination", "class_destination.html", null ],
    [ "ossia::detail::destination_index_retriever", "structossia_1_1detail_1_1destination__index__retriever.html", null ],
    [ "ossia::net::device_base", "classossia_1_1net_1_1device__base.html", null ],
    [ "ossia::net::device_capabilities", "structossia_1_1net_1_1device__capabilities.html", null ],
    [ "ossia::domain", "structossia_1_1domain.html", null ],
    [ "ossia::detail::domain_max_visitor_helper< T >", "structossia_1_1detail_1_1domain__max__visitor__helper.html", null ],
    [ "ossia::detail::domain_min_visitor_helper< T >", "structossia_1_1detail_1_1domain__min__visitor__helper.html", null ],
    [ "ossia::oscquery::detail::domain_to_json", "structossia_1_1oscquery_1_1detail_1_1domain__to__json.html", null ],
    [ "ossia::domain_value_set_creation_visitor", "structossia_1_1domain__value__set__creation__visitor.html", null ],
    [ "ossia::execution_error", "structossia_1_1execution__error.html", null ],
    [ "Ossia.ExposeAttributes", "class_ossia_1_1_expose_attributes.html", null ],
    [ "Ossia.ExposeComponents", "class_ossia_1_1_expose_components.html", null ],
    [ "ossia::expressions::expression_generic_base", "structossia_1_1expressions_1_1expression__generic__base.html", null ],
    [ "ossia::net::full_parameter_data", "structossia_1_1net_1_1full__parameter__data.html", null ],
    [ "ossia::generic_clamp", "structossia_1_1generic__clamp.html", null ],
    [ "ossia::oscquery::get_query_answerer", "classossia_1_1oscquery_1_1get__query__answerer.html", null ],
    [ "Impulse", "class_impulse.html", null ],
    [ "ossia::net::instance_bounds", "structossia_1_1net_1_1instance__bounds.html", null ],
    [ "ossia::invalid_access_error", "structossia_1_1invalid__access__error.html", null ],
    [ "ossia::invalid_callback_error", "structossia_1_1invalid__callback__error.html", null ],
    [ "ossia::invalid_node_error", "structossia_1_1invalid__node__error.html", null ],
    [ "ossia::invalid_value_type_error", "structossia_1_1invalid__value__type__error.html", null ],
    [ "ossia::oscquery::json_parser", "structossia_1_1oscquery_1_1json__parser.html", null ],
    [ "ossia::oscquery::json_query_answerer", "structossia_1_1oscquery_1_1json__query__answerer.html", null ],
    [ "ossia::oscquery::json_writer", "classossia_1_1oscquery_1_1json__writer.html", null ],
    [ "ossia::oscquery::detail::json_writer_impl", "structossia_1_1oscquery_1_1detail_1_1json__writer__impl.html", null ],
    [ "ossia::list_clamp", "structossia_1_1list__clamp.html", null ],
    [ "osc::listener< MessageHandler >", "classosc_1_1listener.html", null ],
    [ "ossia::locked_container< Container >", "classossia_1_1locked__container.html", null ],
    [ "ossia::merger_impl", "structossia_1_1merger__impl.html", null ],
    [ "ossia::message", "structossia_1_1message.html", null ],
    [ "ossia::net::network_logger", "classossia_1_1net_1_1network__logger.html", null ],
    [ "ossia::net::node_base", "classossia_1_1net_1_1node__base.html", null ],
    [ "ossia::node_not_found_error", "structossia_1_1node__not__found__error.html", null ],
    [ "versioneer.NotThisMethod", "classversioneer_1_1_not_this_method.html", null ],
    [ "pyossia._version.NotThisMethod", "classpyossia_1_1__version_1_1_not_this_method.html", null ],
    [ "ossia::oscquery::osc_type_visitor", "structossia_1_1oscquery_1_1osc__type__visitor.html", null ],
    [ "ossia_local_device", "classossia__local__device.html", null ],
    [ "ossia_minuit_device", "classossia__minuit__device.html", null ],
    [ "ossia_osc_device", "classossia__osc__device.html", null ],
    [ "ossia_oscquery_device", "classossia__oscquery__device.html", null ],
    [ "ossia::net::parameter_data", "structossia_1_1net_1_1parameter__data.html", null ],
    [ "ossia::parse_error", "structossia_1_1parse__error.html", null ],
    [ "ossia::regex_path::path_element", "structossia_1_1regex__path_1_1path__element.html", [
      [ "ossia::regex_path::any_between", "structossia_1_1regex__path_1_1any__between.html", null ],
      [ "ossia::regex_path::any_instance", "structossia_1_1regex__path_1_1any__instance.html", null ],
      [ "ossia::regex_path::device", "structossia_1_1regex__path_1_1device.html", null ]
    ] ],
    [ "ossia::net::protocol_base", "classossia_1_1net_1_1protocol__base.html", [
      [ "ossia::net::multiplex_protocol", "classossia_1_1net_1_1multiplex__protocol.html", null ],
      [ "ossia::oscquery::oscquery_server_protocol", "classossia_1_1oscquery_1_1oscquery__server__protocol.html", null ]
    ] ],
    [ "ossia::oscquery::query_parser", "classossia_1_1oscquery_1_1query__parser.html", null ],
    [ "osc::receiver", "classosc_1_1receiver.html", null ],
    [ "osc::sender< T >", "classosc_1_1sender.html", null ],
    [ "ossia::state", "classossia_1_1state.html", null ],
    [ "ossia::regex_path::stop", "structossia_1_1regex__path_1_1stop.html", null ],
    [ "test_.TestAll", "classtest___1_1_test_all.html", null ],
    [ "ossia::time_event", "classossia_1_1time__event.html", null ],
    [ "ossia::time_interval", "classossia_1_1time__interval.html", null ],
    [ "ossia::time_process", "classossia_1_1time__process.html", [
      [ "ossia::automation", "classossia_1_1automation.html", null ],
      [ "ossia::loop", "classossia_1_1loop.html", null ],
      [ "ossia::mapper", "classossia_1_1mapper.html", null ]
    ] ],
    [ "ossia::time_sync", "classossia_1_1time__sync.html", null ],
    [ "ossia::time_value", "structossia_1_1time__value.html", null ],
    [ "ossia::python::to_python_value", "structossia_1_1python_1_1to__python__value.html", null ],
    [ "tsBSpline", "structts_b_spline.html", null ],
    [ "tsDeBoorNet", "structts_de_boor_net.html", null ],
    [ "ossia::unit_t", "structossia_1_1unit__t.html", null ],
    [ "ossia::value", "classossia_1_1value.html", null ],
    [ "ossia::value_with_unit", "structossia_1_1value__with__unit.html", null ],
    [ "versioneer.VersioneerBadRootError", "classversioneer_1_1_versioneer_bad_root_error.html", null ],
    [ "pyossia._version.VersioneerConfig", "classpyossia_1_1__version_1_1_versioneer_config.html", null ],
    [ "versioneer.VersioneerConfig", "classversioneer_1_1_versioneer_config.html", null ],
    [ "ossia::oscquery::websocket_client", "classossia_1_1oscquery_1_1websocket__client.html", null ],
    [ "ossia::websocket_heartbeat", "structossia_1_1websocket__heartbeat.html", null ],
    [ "ossia::websocket_log_sink", "structossia_1_1websocket__log__sink.html", null ],
    [ "ossia::oscquery::websocket_server", "classossia_1_1oscquery_1_1websocket__server.html", null ]
];